config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'admin#user_list'
  
  get 'delete_user' => 'admin#delete_user'

  post 'edit_user' => 'admin#edit_user'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get "delete_item" => 'cart#delete_item'

  post 'edit_quantity' => 'cart#edit_quantity'



  devise_for :users
  root 'storefront#all_items'

  get 'categorical' =>'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	before_action :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart
      line_item = LineItem.find_by(product_id: params[:product_id].to_i)

      #Check to see if the line item exist in the table already. If not, create the line_item
        if line_item.blank?
          line_item = LineItem.create(product_id: params[:product_id].to_i, quantity: params[:quantity].to_i)

      #if it does exist, modify the line item     
        else 
          old_quantity = line_item.quantity  
          line_item.update(quantity: old_quantity + params[:quantity].to_i)
        end  

        line_item.update(line_item_total: line_item.quantity * line_item.product.price)
        redirect_back(fallback_location: root_path)  



  	# line_item = LineItem.create(product_id: params[:product_id].to_i, quantity: params[:quantity].to_i)
  	# line_item.update(line_item_total: line_item.quantity * line_item.product.price)
  	# redirect_back(fallback_location: root_path)
	
  end

  def view_order
  	@line_items = LineItem.all
  end

  def checkout
  	line_items = LineItem.all
  	@order = Order.create(user_id: current_user.id, subtotal: 0)

  	line_items.each do |line_item|
  		line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
  		@order.order_items[line_item.product_id] = line_item.quantity
  		@order.subtotal += line_item.line_item_total
  	end	
  		@order.save
  		@order.update(sales_tax: @order.subtotal * 0.08)
  		@order.update(grand_total: @order.sales_tax + @order.subtotal)
  
  		line_items.destroy_all

  end


  def edit_quantity
    line_item = LineItem.find(params[:id].to_i)
    line_item.update(quantity: params[:quantity].to_i)
    line_item.update(line_item_total: line_item.quantity * line_item.product.price)
    redirect_to view_order_path
  end  


  def delete_item
    line_item = LineItem.find(params[:id].to_i)
    line_item.delete
    redirect_to view_order_path
  end 

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thanks for shopping with us!</h2>
<p>Let's review your order:</p>

<% @order.order_items.each do |k,v| %>
  <ul>
    <li><%= Product.find(k).name %>, <%= v %></li>
  </ul>
<% end %>

<p>
  <strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

app/views/cart/view_order.html.erb
<h3>Here's what in your cart so far:</h3>

<% @line_items.each do |line_item| %>
	<div class="well">
		<p>Item:</p>
		<p><%= line_item.product.name %></p>
		<p>Price: <%= number_to_currency(line_item.product.price) %> each </p>
		

	<p>Current quantity in cart:
  	<%= form_tag edit_quantity_path do %>
  		<%= hidden_field_tag :id, line_item.id %>
  		<%= number_field_tag :quantity, line_item.quantity, max: line_item.product.quantity %>
			<%= submit_tag "Update Quantity", class: "btn btn-success" %>
  	<% end %>
  	<%=  link_to "Remove From Cart", delete_item_path(id: line_item.id), class: "btn btn-danger" %>

  </p>
	<p>Subtotal: <%= number_to_currency(line_item.line_item_total) %></p>
	</div>
<% end %>	

<p><%= link_to "Proceed to Checkout?",checkout_path, class: "btn btn-success" %></p>