config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'admin#user_list'
  
  get 'delete_user' => 'admin#delete_user'

  post 'edit_user' => 'admin#edit_user'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get "delete_item" => 'cart#delete_item'

  post 'edit_quantity' => 'cart#edit_quantity'



  devise_for :users
  root 'storefront#all_items'

  get 'categorical' =>'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  end

  def items_by_category
  	@products = Product.where(category_id: params[:category_id])
  	@category = Category.find(params[:category_id])
  end

  def items_by_brand
  	@products = Product.where(brand: params[:brand])
  	@brand = params[:brand]
	end
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/storefront/_productloop.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well well-storefront">
      	<center>
	        <div class="pic-space" >
	         <center> <p><%= image_tag product.image.url, class: "storefront-pic" %></p></center>
	       	</div>
        <h3 class="modal-name"><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class="glyphicon glyphicon-plus"></span> Quick Info
          </a>
        </p>
      </center>
      </div>
    </div>

    <!-- Modal Info Here -->


    	<!-- Product Modal -->
		<div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
          </div>
          <div class="modal-body">
            <center>
              <p><%= image_tag product.image.show %></p>

            <h3 class="modal-name"><%= link_to product.name, product %></h3>
            <p><%= number_to_currency product.price %></p>
            <p>Made by: <%= product.brand %></p>
            <p>Current Stock: <%= product.quantity %></p>
            <p>
              <% product.rating.times do %>
              <span class="glyphicon glyphicon-star"></span>
            <% end %>
            <% (5 -product.rating).times do %>
              <span class="glyphicon glyphicon-star-empty"></span>
            <% end %>
            </p>
          </center>
          </div>

          <div class="modal-footer">
          	<p>
	          	<%= form_tag add_to_cart_path do %>
	          		<%= hidden_field_tag :product_id, product.id %>
	          		<%= number_field_tag :quantity, nil, min: 1, max: product.quantity %>
								<%= submit_tag "Add to Cart", class: "btn btn-success" %>
	          	<% end %>
	          </p>
          </div>
      </div>
    </div>


<!-- End modal info -->
</div>
  <% end %>

</div>

app/views/storefront/all_items.html.erb
<div>
  <div class="alert">
    <% if alert %>
      <%=  alert %>
    <% end %> 
  </div>
  <%= render 'productloop' %>
</div>

app/views/storefront/items_by_brand.html.erb
<h3>Here are the items made by <%= @brand %>: </h3>

<div>
  <%= render 'productloop' %>
</div>

app/views/storefront/items_by_category.html.erb
<h3>Here are the products in our <%= @category.name %> department:</h3>

<div>
  <%= render 'productloop' %>
</div>