config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'admin#user_list'
  
  get 'delete_user' => 'admin#delete_user'

  post 'edit_user' => 'admin#edit_user'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get "delete_item" => 'cart#delete_item'

  post 'edit_quantity' => 'cart#edit_quantity'



  devise_for :users
  root 'storefront#all_items'

  get 'categorical' =>'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jun2018Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  	  	<!-- Start of nav bar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <!-- Links to our list of all products -->
            <li><%= link_to " All Products", root_path %></li>

            <!-- provides a dropdown of all our categories  -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @categories.each do |category| %>
                  <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
                <% end %>
              </ul>
            </li>


            <!-- provides a dropdown for all our brands -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @brands.each do |brand| %>
                  <li><%= link_to brand, branding_path(brand: brand) %></li>
                <% end %>
              </ul>
            </li>


            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome <%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li> 
            <% else %>
              <li><%= link_to "Sign In", user_session_path  %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>  

            <% if user_signed_in? && current_user.role == "admin" %>
             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
              <ul class="dropdown-menu">
                
              <li><%= link_to "Users List", users_path %></li>
              <li><%= link_to "Inventory Page", products_path %></li>
                <% end %>
              </ul>
            </li>

          </ul>




          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "View Cart", view_order_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<!-- End of Nav bar -->



    <div class="padded">
    	<h1 class="title">Welcome to SpreeShopper</h1>
  		<h4 class= "title2">Make every experience a shopping spree!</h4>
  	</div> 



  	<div class="container body-padding">
	    <%= yield %>
	   </div> 
  </body>
</html>